blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.list_of_post, name = 'list_all_post'),
	url(r'^(?P<slug>[-\w]+)/$', views.post_detail, name = 'post_detail'),
	url(r'^category/(?P<category_slug>[-\w]+)/$', views.list_of_post_by_category, name = 'list_of_post_by_category'),
	url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name = 'add_comment'),
	url(r'^backend/post/new/$', views.new_post, name='new_post'),
	url(r'^backend/post/$', views.list_of_post_backend, name='list_of_post_backend'),
	url(r'^backend/(?P<slug>[-\w]+)/edit/$', views.edit_post, name='edit_post'),
	url(r'^backend/(?P<slug>[-\w]+)/delete/$', views.delete_post, name='delete_post'),
]

cms/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog' ))
]

todoapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.list_of_todos_all, name='list_of_todos'),
	url(r'^list_of_todos/active$', views.list_of_todos_active, name='list_of_todos_active'),
	url(r'^list_of_todos/completed$', views.list_of_todos_completed, name='list_of_todos_completed'),
	url(r'^(?P<id>[\d]+)/$', views.todo_detail, name='todo_detail'),
	url(r'^(?P<id>[\d]+)/delete$', views.todo_delete, name='todo_delete'),
	url(r'^(?P<id>[\d]+)/completed$', views.todo_completed, name='todo_completed'),
	url(r'^todo_add$', views.todo_add, name='todo_add'),
]

todoapp/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User

# Create your models here.
class Todo(models.Model):
	STATUS_CHOICES = (
		('active', 'Active'),
		('completed', 'Completed'),
	)
	title = models.CharField(max_length=50)
	created_by = models.ForeignKey(User, related_name='todo_apps')
	completed = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='active')

	def get_absolute_url(self):
		return reverse('todoapp:todo_detail', args=[self.id])

	def __str__(self):
		return self.title

todoapp/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
	class Meta:
		model = Todo
		fields = ('title',) 

todoapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.contrib import messages

from .models import Todo

from .forms import TodoForm

# Create your views here.

def list_of_todos_all(request):
	todos = Todo.objects.all()
	context = {'todos': todos}
	template = 'todoapp/todo/list_of_todos.html'
	return render(request, template, context)

def list_of_todos_active(request):
	todos = Todo.objects.filter(status='active')
	context = {'todos': todos}
	template = 'todoapp/todo/list_of_todos_active.html'
	return render(request, template, context)

def list_of_todos_completed(request):
	todos = Todo.objects.filter(status='completed')
	context = {'todos': todos}
	template = 'todoapp/todo/list_of_todos_completed.html'
	return render(request, template, context)

def todo_detail(request, id):
	todo = get_object_or_404(Todo, id=id)
	template = 'todoapp/todo/todo_detail.html'
	context = {'todo': todo}
	return render(request, template, context)

def todo_delete(request, id):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	todo = get_object_or_404(Todo, id=id)
	todo.delete()
	messages.success(request, "Successfully Deleted")
	return redirect('todoapp:list_of_todos_completed')

def todo_completed(request, id):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	todo = get_object_or_404(Todo, id=id)
	todo.status = 'completed'
	todo.save()
	return redirect('todoapp:list_of_todos_completed')

def todo_add(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	if request.method == "POST":
		form = TodoForm(request.POST)
		if form.is_valid():
			todo = form.save(commit=False)
			todo.created_by = request.user
			todo.save()
			return redirect('todoapp:list_of_todos')
	else:
		form = TodoForm()

	template = 'todoapp/todo/todo_add.html'
	context = {'form': form}
	return render(request, template, context)

todoapp/templates/todoapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
		<title>
			{% block title %} {% endblock %}
		</title>
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<style>
			body {
			  padding-top: 3rem;
			}
			header {
				padding-top: 3rem;
			}
		</style>
	</head>
	<body>
		{% include 'todoapp/header.html' with page_name="todo" %}
		<main role="main" class="container">
			<div class="container">
				{% include 'blog/messages.html' %}
				{% block content %} {% endblock %}
			</div>
		</main>
		<!-- JS Files -->
		<script type="text/javascript" src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
	</body>
</html>

todoapp/templates/todoapp/header.html
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <!-- <a class="navbar-brand" href="#">Fixed navbar</a> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse float-right" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
      	{% if page_name == "todo" %}
	        <li class="nav-item active">
	          <a class="nav-link" href="#">Todo <span class="sr-only">(current)</span></a>
	        </li>
        {% else %}
        	<li class="nav-item">
         		<a class="nav-link" href="{% url 'todoapp:list_of_todos' %}">Todo</a>
        	</li>
        {% endif %}
        {% if page_name == "blog" %}
	        <li class="nav-item active">
          	<a class="nav-link" href="#">Blog <span class="sr-only">(current)</span></a>
        	</li>
        {% else %}
        	<li class="nav-item">
          	<a class="nav-link" href="{% url 'blog:list_all_post' %}">Blog </a>
        	</li>
        {% endif %}
       
      </ul>
    </div>
  </nav>
</header>

todoapp/templates/todoapp/messages.html
{% if messages %}
	{% for message in messages %}
		{% if message.tags %}
			<div class="alert alert-{{message.tags}}">{{message}}</div>
		{% endif %}
	{% endfor %}
{% endif %}