blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.list_of_post, name = 'list_all_post'),
	url(r'^(?P<slug>[-\w]+)/$', views.post_detail, name = 'post_detail'),
	url(r'^category/(?P<category_slug>[-\w]+)/$', views.list_of_post_by_category, name = 'list_of_post_by_category'),
	url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name = 'add_comment'),
	url(r'^backend/post/new/$', views.new_post, name='new_post'),
	url(r'^backend/post/$', views.list_of_post_backend, name='list_of_post_backend'),
	url(r'^backend/(?P<slug>[-\w]+)/edit/$', views.edit_post, name='edit_post'),
	url(r'^backend/(?P<slug>[-\w]+)/delete/$', views.delete_post, name='delete_post'),
]

cms/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog' ))
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify 

from django.contrib.auth.models import User
# Create your models here.

# Category
class Category(models.Model):
	name = models.CharField(max_length = 250)
	slug = models.SlugField(max_length = 250, unique = True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('blog:list_of_post_by_category', args=[self.slug])

# Post		
class Post(models.Model):
	STATUS_CHOICES = (
		('draft', 'Draft'),
		('published', 'Published')
	)
	category = models.ForeignKey(Category)
	title = models.CharField(max_length = 250)
	slug = models.SlugField(max_length = 250, unique = True)
	content = models.TextField()
	seo_title = models.CharField(max_length = 250)
	seo_description = models.CharField(max_length = 160)
	author = models.ForeignKey(User, related_name = 'blog_posts')
	published = models.DateTimeField(default = timezone.now)
	created = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True)
	status = models.CharField(max_length = 9, choices = STATUS_CHOICES, default =  'draft')

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Post, self).save(*args, **kwargs)


	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[self.slug])

	def __str__(self):
		return self.title

#Comment
class Comment(models.Model):
	post = models.ForeignKey(Post, related_name = 'comments')
	user = models.CharField(max_length = 250)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add = True)
	aprroved = models.BooleanField(default = False)

	def approved(self):
		self.approved = True
		self.save()

	def __str__(self):
		return self.user

blog/forms.py
from django import forms
from .models import Comment, Post

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('user', 'email', 'body')

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'content',  'category', 'seo_title', 'seo_description', 'status') 

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.contrib import messages

from .models import Post, Category

from .forms import CommentForm, PostForm
# Create your views here.

def list_of_post_by_category(request, category_slug):
	categories = Category.objects.all();
	posts = Post.objects.filter(status='published')
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		posts = Post.objects.filter(category=category)
	template = 'blog/category/list_of_post_by_category.html'
	context = {'categories':categories, 'posts': posts, 'category': category}
	return render(request, template, context)

def list_of_post(request):
	posts = Post.objects.filter(status='published')
	paginator = Paginator(posts, 1)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	template = 'blog/post/list_of_post.html'
	context = {'posts': posts, 'page': page}
	return render(request, template, context)

def post_detail(request, slug):
	post = get_object_or_404(Post, slug=slug)
	if post.status == 'published':
		template = 'blog/post/post_detail.html'
	else:
		template = 'blog/post/post_preview.html'
	context = {'post': post}
	return render(request, template, context)

def add_comment(request, slug):
	post = get_object_or_404(Post, slug=slug)

	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.save()
			return redirect('blog:post_detail', slug=post.slug)
	else:
		form = CommentForm()

	template = 'blog/post/add_comment.html'
	context = {'form': form}
	return render(request, template, context) 

#########################################
##############  Backend #################
#########################################

def new_post(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
			return redirect('blog:post_detail', slug=post.slug)
	else:
		form = PostForm()

	template = 'blog/backend/new_post.html'
	context = {'form': form}
	return render(request, template, context)

def list_of_post_backend(request):
	posts = Post.objects.all()
	paginator = Paginator(posts, 20)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	template = 'blog/backend/list_of_post_backend.html'
	context = {'posts': posts, 'page': page}
	return render(request, template, context)

def edit_post(request, slug):
	post = get_object_or_404(Post, slug=slug)
	if request.method == "POST":
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
			return redirect('blog:list_of_post_backend')
	else:
		form = PostForm(instance=post)
	context = {'form': form}
	template = 'blog/backend/new_post.html'
	return render(request, template, context)

def delete_post(request, slug):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	post = get_object_or_404(Post, slug=slug)
	post.delete()
	messages.success(request, "Successfully Deleted")
	return redirect('blog:list_of_post_backend')

blog/templates/blog/backend/list_of_post_backend.html
{% extends 'blog/base.html' %}

{% block title %} List of posts from Backend {% endblock %}

{% block content %}
	<div class="responsive">
		<table class="table table-hover">
			<tr>
				<th>Title</th>
				<th>Slug</th>
				<th>Author</th>
				<th>Published</th>
				<th>status</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			{% for post in posts %}
				{% if post.status == 'draft' %}
					<tr class="table-danger">
						<td>{{ post.title }}</td>
						<td>{{ post.slug }}</td>
						<td>{{ post.author }}</td>
						<td>{{ post.published }}</td>
						<td>{{ post.status }}</td>
						<td><a href="{% url 'blog:edit_post' slug=post.slug %}" class="btn btn-primary">Edit</a></td>
						<td><a href="{% url 'blog:delete_post' slug=post.slug %}" class="btn btn-danger">Delete</a></td>
					</tr>
				{% else %}
					<tr>
						<td>{{ post.title }}</td>
						<td>{{ post.slug }}</td>
						<td>{{ post.author }}</td>
						<td>{{ post.published }}</td>
						<td>{{ post.status }}</td>
						<td><a href="{% url 'blog:edit_post' slug=post.slug %}" class="btn btn-primary">Edit</a></td>
						<td><a href="{% url 'blog:delete_post' slug=post.slug %}" class="btn btn-danger">Delete</a></td>
					</tr>
				{% endif %}
			{% endfor %}
		</table>
		{% include 'blog/paginator.html' with page=posts %}
	</div>

{% endblock %}

blog/templates/blog/backend/new_post.html
{% extends 'blog/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

	<h1>New Post </h1>

	<form method="POST" class="post-form">{% csrf_token %}
		{{ form|crispy }}
		<button type="submit" class="btn btn-success float-right">Submit</button>
	</form>


{% endblock %}